---
- hosts: all
  sudo: true
  sudo_user: root
  vars:
    locale: en_US.UTF-8
    timezone: UTC
    gitlab_root: /home/git/gitlab-shell
  vars_files:
    - .user-configurations.yml

  tasks:
  - name: dev locale
    action: command sudo update-locale LC_ALL=en_US.UTF-8

  - name: set default English
    command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }} LANGUAGE=en_US:en

  - name: set /etc/localtime to UTC Timezone
    command: /bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime

  - name: apt-get update the server
    apt: update_cache=yes

  - name: Create a 4.5G swap file
    command: "{{item}}"
    with_items:
      - "sudo dd if=/dev/zero of=/swapfile bs=500M count=9 conv=notrunc,noerror"
      - "sudo chmod 600 /swapfile"
      - "sudo mkswap /swapfile"
      - "sudo swapoff -a"
      - "sudo swapon /swapfile"

  - name: Make the swapfile permanent
    lineinfile: >
                  dest=/etc/fstab
                  line="/swapfile  none  swap  sw  0  0"

  - name: install packages
    apt: name={{item}} state=present
    with_items:
      - debhelper
      - git
      - vim
      - curl
      - tree
      - cmake
      - nodejs
      - build-essential
      - zlib1g-dev
      - libyaml-dev
      - libssl-dev
      - libgdbm-dev
      - libreadline-dev
      - libncurses5-dev
      - libffi-dev
      - openssh-server
      - redis-server
      - checkinstall
      - libxml2-dev
      - libxslt-dev
      - libcurl4-openssl-dev
      - libicu-dev

  - name: Add the git user account
    command: sudo adduser --disabled-login --gecos 'GitLab' git

  - name: Clone the git repository
    command: sudo git clone https://github.com/gitlabhq/gitlab-shell.git
    args:
      chdir: /home/git/

  - name: Run the git script to set up the gitlab config file after cloning
    command: "{{item}}"
    args:
      chdir: /home/git/gitlab-shell
    with_items:
      - sudo git checkout v1.7.0
      - sudo cp config.yml.example config.yml

  - name: replace the local configuration of the local host
    lineinfile: >
                dest=/home/git/gitlab-shell/config.yml 
                regexp='gitlab_url' 
                line="gitlab_url: \"{{GITLAB_URL}}\"" 
                owner=root 
                group=root

  - name: Make the ruby tmp directory
    file: path=/tmp/ruby state=directory mode=0770

  - name: Download the ruby package and untar
    command: "{{item}}"
    args:
      chdir: /tmp/ruby
    with_items:
      - wget http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p247.tar.gz
      - tar -xvzf ruby-2.0.0-p247.tar.gz

  - name: Configure ruby
    command: "{{item}}"
    args:
      chdir: /tmp/ruby/ruby-2.0.0-p247
    with_items:
      - ./configure
      - make
      - sudo make install

  - name: Install the Bundler gem
    command: sudo gem install bundler --no-ri --no-rdoc

  - name: Change file ownerships to git user
    command: sudo chown -R git:git /home/git/gitlab-shell

  - name: Run the installation
    command: sudo -u git -H ./bin/install
    args:
      chdir: "{{gitlab_root}}"

- include: mySQL-playbook.yml
- include: gitlab.yml
- include: nginx-config.yml

